export const INITIALIZE_QUEUE = 'INITIALIZE_QUEUE'
export const ADD_TO_QUEUE = 'ADD_TO_QUEUE'
export const REMOVE_FROM_QUEUE = 'REMOVE_FROM_QUEUE'

export const CREATE_WIDGET = 'CREATE_WIDGET'
export const REMOVE_WIDGET = 'REMOVE_WIDGET'

export const INITIALIZE_DATE_AND_TIME = 'INITIALIZE_DATE_AND_TIME'
export const UPDATE_DATE_AND_TIME = 'UPDATE_DATE_AND_TIME'
